[WIP] chore: Reorganize project files as a Python project
RedHatInsights/vmaas pull request #839
Opened 2021-05-10 14:31 UTC by Josca

2021-05-11 17:55 UTC, psegedy requested changes
deploy fails - at first sight it looks like init container is crashing because of https://github.com/RedHatInsights/vmaas/blob/master/deploy/clowdapp.yaml#L125
Edit: if we want to make it work in CI and QA envs it will probably need appropriate changes in e2e-deploy repo

2021-05-12 08:48 UTC, Josca commented
/retest

2021-05-12 11:15 UTC, psegedy approved these changes

2021-05-17 10:30 UTC, jdobes approved these changes

2021-05-17 10:30 UTC, merged