Draft: feat(updates): look up updates by repository paths
RedHatInsights/vmaas pull request #977
Opened 2022-11-09 16:17 UTC by vkrizan

Provide an option to look up updates and vulnerabilities by providing
repository paths (as an addition to repository labels).

This should support tracking updates and vulnerabilities within RHUI
enabled machines, as it would not be dependent on repository labels.

This also adds a new cache `repopath2ids`.

VULN-2443

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

2022-11-18 11:30 UTC, vkrizan commented
/retest

2022-11-21 12:49 UTC, vkrizan commented
/retest

2022-11-21 14:40 UTC, jdobes requested changes

2022-11-22 15:34 UTC, vkrizan commented on vmaas/webapp/webapp.v3.spec.yaml
> +        repository_paths:
Added.

2022-11-22 16:30 UTC, merged